version: '3.5'

networks:
    monitoring_network:

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        networks:
            - monitoring_network
        volumes:
            - /data/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /data/prometheus_data:/prometheus
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=90d'
            - '--storage.tsdb.retention.size=50GB'
        restart: unless-stopped


    grafana:
        container_name: grafana
        image: grafana/grafana
        networks:
            - monitoring_network
        volumes:
            - /data/configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - /data/configs/grafana/provisioning/datasources/config.yml:/etc/grafana/provisioning/datasources/config.yml
            - /data/grafana_data:/etc/grafana
        environment:
            - TERM=linux
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=finicast
        ports:
            - "3000:3000"
        restart: unless-stopped

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        networks:
            - monitoring_network
        ports:
            - "9100:9100"
        expose:
            - "9100"
        restart: unless-stopped
