---

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'sv2a-devb7:9100'
        - 'sv2a-devb8:9100'
        - 'sv2a-devb9:9100'
