---
- apt_repository:
    repo: 'ppa:ansible/ansible'

- name: apt update
  ansible.builtin.shell: |
    apt update

- name: install ansible
  ansible.builtin.apt:
    name: ansible
    state: present

- name: update ansible.cfg
  ansible.builtin.replace:
    path: '/etc/ansible/ansible.cfg'
    regexp: '#host_key_checking = False'
    replace: host_key_checking = False
    backup: yes
  tags: update_ansible_cfg
