---
- name: install ara
  hosts: all
  gather_facts: yes
  #  become_method: sudo
  become: yes
  roles:
    - role: ara_web
      tags: ara_web_install
      
    - role: ara_api
      tags: ara_api_install

    - role: ara_frontend_nginx
      tags: ara_frontend_nginx_install
