---
# tasks file for ansible-server
- name: add the official project’s PPA of ansible/ansible
  ansible.builtin.shell: |
    apt-add-repository ppa:ansible/ansible

- name: apt update
  ansible.builtin.shell: |
    apt update

- name: install ansible
  ansible.builtin.apt:
    name: ansible
    state: present

- name: update ansible.cfg
  ansible.builtin.replace:
    path: '/etc/ansible/ansible.cfg'
    regexp: #host_key_checking = False
    replace: host_key_checking = False
    backup: yes
  tags: update_ansible_cfg

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key
  community.crypto.openssh_keypair:
    path: /tmp/id_ssh_rsa
    passphrase: "{{ ansible_key_pass }}"